#!/bin/sh

status="$(pulseaudio-ctl full-status)"
vol="$(echo $status | cut -d' ' -f1)"
mute="$(echo $status | cut -d' ' -f2)"
if [ "$mute" = "yes" ]
then
	echo "%{A:pavucontrol:}%{B#21262d}%{F#89b482}%{+u}  %{-u}%{F}%{B}%{A}"
else
	if [ "$vol" -ge 100 ]
	then
		symbol=""
	elif [ "$vol" -ge 50 ]
	then
		symbol=""
	else
		symbol=""
	fi
	echo "%{A:pavucontrol:}%{B#21262d}%{F#89b482}%{+u} $symbol$vol %{-u}%{F}%{B}%{A}"
fi
