#!/bin/sh

read cpu a b c previdle rest < /proc/stat
prevtotal=$((a+b+c+previdle))
sleep 0.5
read cpu a b c idle rest < /proc/stat
total=$((a+b+c+idle))
cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
echo "%{A:$TERMINAL -e htop:}%{B#21262d}%{F#7daea3}%{+u} CPU:$cpu% %{-u}%{F}%{B}%{A}"
