#!/bin/sh
capacity=$(cat /sys/class/power_supply/BAT0/capacity)

if [ "$capacity" -ge 80 ]
then
    symbol=""

elif [ "$capacity" -ge 60 ]
then
    symbol=""

elif [ "$capacity" -ge 40 ]
then
    symbol=""

elif [ "$capacity" -ge 20 ]
then
    symbol=""
else
    symbol=""
fi
echo "%{B#21262d}%{F#a9b665}%{+u} $symbol $capacity% %{-u}%{F}%{B}"
unset symbol
